# ----------------------- #
#      Main Configs       #
# ----------------------- #

url:  https://eliasdefrancisco.github.io/LoroCam #http://www.lorocam.com/
title: LoroCam App
email: eliasdefrancisco@gmail.com
author: Elias de Francisco Javaloyes
description: >
  Add sound effects to your videos while you are recording them
  with LoroCam video camera app for Android. Laughs, applauses,
  robots, dog barking and lots of sounds can be added easily.
copyright: #'Copyright &copy; 2016 Elias de Francisco Javaloyes. All Rights Reserved.'
credits: #'Credits: LoroCam is created by <a href="https://github.com/eliasdefrancisco/">My GitHub</a>. I hope you like it!'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://eliasdefrancisco.github.io/LoroCam/
  - title: googleplay
    url: https://play.google.com/store/apps/details?id=com.arcadexxi.lorocam_sdk22
